/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FbsAuthModal {
    'dbKey': string;
    'mode': string;
    'open': () => Promise<void>;
    'opened': boolean;
  }
  interface FbsDbTree {
    'dbPath': string;
  }
  interface FbsSpinner {}
}

declare global {


  interface HTMLFbsAuthModalElement extends Components.FbsAuthModal, HTMLStencilElement {}
  var HTMLFbsAuthModalElement: {
    prototype: HTMLFbsAuthModalElement;
    new (): HTMLFbsAuthModalElement;
  };

  interface HTMLFbsDbTreeElement extends Components.FbsDbTree, HTMLStencilElement {}
  var HTMLFbsDbTreeElement: {
    prototype: HTMLFbsDbTreeElement;
    new (): HTMLFbsDbTreeElement;
  };

  interface HTMLFbsSpinnerElement extends Components.FbsSpinner, HTMLStencilElement {}
  var HTMLFbsSpinnerElement: {
    prototype: HTMLFbsSpinnerElement;
    new (): HTMLFbsSpinnerElement;
  };
  interface HTMLElementTagNameMap {
    'fbs-auth-modal': HTMLFbsAuthModalElement;
    'fbs-db-tree': HTMLFbsDbTreeElement;
    'fbs-spinner': HTMLFbsSpinnerElement;
  }
}

declare namespace LocalJSX {
  interface FbsAuthModal {
    'dbKey'?: string;
    'mode'?: string;
    'onFbsAuthenticated'?: (event: CustomEvent<any>) => void;
    'opened'?: boolean;
  }
  interface FbsDbTree {
    'dbPath'?: string;
    'onFbsDbPathSelected'?: (event: CustomEvent<string>) => void;
  }
  interface FbsSpinner {}

  interface IntrinsicElements {
    'fbs-auth-modal': FbsAuthModal;
    'fbs-db-tree': FbsDbTree;
    'fbs-spinner': FbsSpinner;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'fbs-auth-modal': LocalJSX.FbsAuthModal & JSXBase.HTMLAttributes<HTMLFbsAuthModalElement>;
      'fbs-db-tree': LocalJSX.FbsDbTree & JSXBase.HTMLAttributes<HTMLFbsDbTreeElement>;
      'fbs-spinner': LocalJSX.FbsSpinner & JSXBase.HTMLAttributes<HTMLFbsSpinnerElement>;
    }
  }
}


